"""initial schema

Revision ID: cd35edd96629
Revises:
Create Date: 2026-08-05 02:17:29.538810
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cd35edd96629"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cache_key", sa.String(length=80), nullable=False),
        sa.Column("view", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insights")),
        sa.UniqueConstraint("cache_key", name=op.f("uq_insights_cache_key")),
    )
    op.create_table(
        "job_ledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_key", sa.String(length=100), nullable=False),
        sa.Column("period_key", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("ran_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_ledger")),
        sa.UniqueConstraint(
            "job_key", "period_key", name=op.f("uq_job_ledger_job_key_period_key")
        ),
    )
    op.create_table(
        "orgs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=300), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "repo_filter_mode",
            sa.Enum(
                "ALL",
                "WHITELIST",
                "BLACKLIST",
                name="filtermode",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "person_filter_mode",
            sa.Enum(
                "ALL",
                "WHITELIST",
                "BLACKLIST",
                name="filtermode",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("sync_status", sa.String(length=20), nullable=False),
        sa.Column("sync_error", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orgs")),
    )
    op.create_index(op.f("ix_orgs_login"), "orgs", ["login"], unique=True)
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_persons")),
    )
    op.create_table(
        "recipients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipients")),
        sa.UniqueConstraint("email", name=op.f("uq_recipients_email")),
    )
    op.create_table(
        "report_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period_kind", sa.String(length=20), nullable=False),
        sa.Column("report_kind", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "org_scope",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_schedules")),
        sa.UniqueConstraint(
            "period_kind",
            "report_kind",
            name=op.f("uq_report_schedules_period_kind_report_kind"),
        ),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("period_kind", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "org_scope",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("subject_type", sa.String(length=20), nullable=True),
        sa.Column("subject_id", sa.Integer(), nullable=True),
        sa.Column("pdf_path", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("emailed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "GIT_AUTHOR",
                "GITHUB_LOGIN",
                name="identitykind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("login", sa.String(length=200), nullable=True),
        sa.Column("name_norm", sa.String(length=300), nullable=False),
        sa.Column("email_norm", sa.String(length=320), nullable=False),
        sa.Column("login_norm", sa.String(length=200), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
            name=op.f("fk_identities_person_id_persons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identities")),
    )
    op.create_index(
        "ix_identities_git_author_key",
        "identities",
        ["name_norm", "email_norm"],
        unique=True,
        postgresql_where="kind = 'git_author'",
        sqlite_where="kind = 'git_author'",
    )
    op.create_index(
        "ix_identities_github_login_key",
        "identities",
        ["login_norm"],
        unique=True,
        postgresql_where="kind = 'github_login'",
        sqlite_where="kind = 'github_login'",
    )
    op.create_index(
        op.f("ix_identities_person_id"), "identities", ["person_id"], unique=False
    )
    op.create_table(
        "merge_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_a_id", sa.Integer(), nullable=False),
        sa.Column("person_b_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "reasons",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_a_id"],
            ["persons.id"],
            name=op.f("fk_merge_suggestions_person_a_id_persons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_b_id"],
            ["persons.id"],
            name=op.f("fk_merge_suggestions_person_b_id_persons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merge_suggestions")),
        sa.UniqueConstraint(
            "person_a_id",
            "person_b_id",
            name=op.f("uq_merge_suggestions_person_a_id_person_b_id"),
        ),
    )
    op.create_index(
        op.f("ix_merge_suggestions_person_a_id"),
        "merge_suggestions",
        ["person_a_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_merge_suggestions_person_b_id"),
        "merge_suggestions",
        ["person_b_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_merge_suggestions_status"),
        "merge_suggestions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "org_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("token_encrypted", sa.Text(), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "rate_snapshot",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
            name=op.f("fk_org_credentials_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_credentials")),
        sa.UniqueConstraint("org_id", name=op.f("uq_org_credentials_org_id")),
    )
    op.create_table(
        "person_filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
            name=op.f("fk_person_filters_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
            name=op.f("fk_person_filters_person_id_persons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_filters")),
        sa.UniqueConstraint(
            "org_id", "person_id", name=op.f("uq_person_filters_org_id_person_id")
        ),
    )
    op.create_index(
        op.f("ix_person_filters_org_id"), "person_filters", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_person_filters_person_id"),
        "person_filters",
        ["person_id"],
        unique=False,
    )
    op.create_table(
        "repo_filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("repo_name", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
            name=op.f("fk_repo_filters_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repo_filters")),
        sa.UniqueConstraint(
            "org_id", "repo_name", name=op.f("uq_repo_filters_org_id_repo_name")
        ),
    )
    op.create_index(
        op.f("ix_repo_filters_org_id"), "repo_filters", ["org_id"], unique=False
    )
    op.create_table(
        "repos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("default_branch", sa.String(length=200), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("is_fork", sa.Boolean(), nullable=False),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.Column(
            "clone_status",
            sa.Enum(
                "PENDING",
                "CLONING",
                "READY",
                "ERROR",
                name="clonestatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("clone_error", sa.Text(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_ingested_oid", sa.String(length=64), nullable=True),
        sa.Column("pr_cursor", sa.String(length=200), nullable=True),
        sa.Column("pr_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
            name=op.f("fk_repos_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repos")),
        sa.UniqueConstraint("node_id", name=op.f("uq_repos_node_id")),
        sa.UniqueConstraint("org_id", "name", name=op.f("uq_repos_org_id_name")),
    )
    op.create_index(op.f("ix_repos_included"), "repos", ["included"], unique=False)
    op.create_index(op.f("ix_repos_org_id"), "repos", ["org_id"], unique=False)
    op.create_table(
        "schedule_recipients",
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["recipients.id"],
            name=op.f("fk_schedule_recipients_recipient_id_recipients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["report_schedules.id"],
            name=op.f("fk_schedule_recipients_schedule_id_report_schedules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "schedule_id", "recipient_id", name=op.f("pk_schedule_recipients")
        ),
    )
    op.create_table(
        "commits",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("oid", sa.String(length=64), nullable=False),
        sa.Column("authored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("author_identity_id", sa.Integer(), nullable=False),
        sa.Column("message_subject", sa.String(length=300), nullable=False),
        sa.Column("additions", sa.Integer(), nullable=False),
        sa.Column("deletions", sa.Integer(), nullable=False),
        sa.Column("files_changed", sa.Integer(), nullable=False),
        sa.Column("is_merge", sa.Boolean(), nullable=False),
        sa.Column("is_mechanical", sa.Boolean(), nullable=False),
        sa.Column("significance", sa.Float(), nullable=False),
        sa.Column("churn_lines", sa.Integer(), nullable=False),
        sa.Column("self_churn_lines", sa.Integer(), nullable=False),
        sa.Column("cross_churn_lines", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_identity_id"],
            ["identities.id"],
            name=op.f("fk_commits_author_identity_id_identities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
            name=op.f("fk_commits_repo_id_repos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commits")),
        sa.UniqueConstraint("repo_id", "oid", name=op.f("uq_commits_repo_id_oid")),
    )
    op.create_index(
        "ix_commits_author_authored",
        "commits",
        ["author_identity_id", "authored_at"],
        unique=False,
    )
    op.create_index(
        "ix_commits_repo_authored", "commits", ["repo_id", "authored_at"], unique=False
    )
    op.create_table(
        "person_repo_day_stats",
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("commits", sa.Integer(), nullable=False),
        sa.Column("additions", sa.Integer(), nullable=False),
        sa.Column("deletions", sa.Integer(), nullable=False),
        sa.Column("churn", sa.Integer(), nullable=False),
        sa.Column("self_churn", sa.Integer(), nullable=False),
        sa.Column("cross_churn", sa.Integer(), nullable=False),
        sa.Column("significance", sa.Float(), nullable=False),
        sa.Column("prs_opened", sa.Integer(), nullable=False),
        sa.Column("prs_merged", sa.Integer(), nullable=False),
        sa.Column("reviews", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
            name=op.f("fk_person_repo_day_stats_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
            name=op.f("fk_person_repo_day_stats_person_id_persons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
            name=op.f("fk_person_repo_day_stats_repo_id_repos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "person_id", "repo_id", "day", name=op.f("pk_person_repo_day_stats")
        ),
    )
    op.create_index(
        "ix_prds_org_day", "person_repo_day_stats", ["org_id", "day"], unique=False
    )
    op.create_index(
        "ix_prds_repo_day", "person_repo_day_stats", ["repo_id", "day"], unique=False
    )
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=True),
        sa.Column("author_identity_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("state", sa.String(length=10), nullable=False),
        sa.Column("created_at_gh", sa.DateTime(timezone=True), nullable=False),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("additions", sa.Integer(), nullable=False),
        sa.Column("deletions", sa.Integer(), nullable=False),
        sa.Column("changed_files", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_identity_id"],
            ["identities.id"],
            name=op.f("fk_pull_requests_author_identity_id_identities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
            name=op.f("fk_pull_requests_repo_id_repos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pull_requests")),
        sa.UniqueConstraint(
            "repo_id", "number", name=op.f("uq_pull_requests_repo_id_number")
        ),
    )
    op.create_index(
        "ix_pull_requests_repo_created",
        "pull_requests",
        ["repo_id", "created_at_gh"],
        unique=False,
    )
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "stats",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
            name=op.f("fk_sync_runs_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
            name=op.f("fk_sync_runs_repo_id_repos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    op.create_index(op.f("ix_sync_runs_org_id"), "sync_runs", ["org_id"], unique=False)
    op.create_table(
        "commit_files",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("commit_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("authored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("old_path", sa.String(length=1024), nullable=True),
        sa.Column("additions", sa.Integer(), nullable=False),
        sa.Column("deletions", sa.Integer(), nullable=False),
        sa.Column(
            "file_class",
            sa.Enum(
                "CODE",
                "TESTS",
                "CONFIG",
                "DOCS",
                "GENERATED",
                name="fileclass",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commits.id"],
            name=op.f("fk_commit_files_commit_id_commits"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
            name=op.f("fk_commit_files_repo_id_repos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commit_files")),
    )
    op.create_index(
        op.f("ix_commit_files_commit_id"), "commit_files", ["commit_id"], unique=False
    )
    op.create_index(
        "ix_commit_files_repo_path_authored",
        "commit_files",
        ["repo_id", "path", "authored_at"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("pull_request_id", sa.BigInteger(), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=True),
        sa.Column("reviewer_identity_id", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pull_request_id"],
            ["pull_requests.id"],
            name=op.f("fk_reviews_pull_request_id_pull_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_identity_id"],
            ["identities.id"],
            name=op.f("fk_reviews_reviewer_identity_id_identities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("node_id", name=op.f("uq_reviews_node_id")),
    )
    op.create_index(
        op.f("ix_reviews_pull_request_id"), "reviews", ["pull_request_id"], unique=False
    )
    op.create_index(
        "ix_reviews_reviewer_submitted",
        "reviews",
        ["reviewer_identity_id", "submitted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reviews_reviewer_submitted", table_name="reviews")
    op.drop_index(op.f("ix_reviews_pull_request_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_commit_files_repo_path_authored", table_name="commit_files")
    op.drop_index(op.f("ix_commit_files_commit_id"), table_name="commit_files")
    op.drop_table("commit_files")
    op.drop_index(op.f("ix_sync_runs_org_id"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_index("ix_pull_requests_repo_created", table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index("ix_prds_repo_day", table_name="person_repo_day_stats")
    op.drop_index("ix_prds_org_day", table_name="person_repo_day_stats")
    op.drop_table("person_repo_day_stats")
    op.drop_index("ix_commits_repo_authored", table_name="commits")
    op.drop_index("ix_commits_author_authored", table_name="commits")
    op.drop_table("commits")
    op.drop_table("schedule_recipients")
    op.drop_index(op.f("ix_repos_org_id"), table_name="repos")
    op.drop_index(op.f("ix_repos_included"), table_name="repos")
    op.drop_table("repos")
    op.drop_index(op.f("ix_repo_filters_org_id"), table_name="repo_filters")
    op.drop_table("repo_filters")
    op.drop_index(op.f("ix_person_filters_person_id"), table_name="person_filters")
    op.drop_index(op.f("ix_person_filters_org_id"), table_name="person_filters")
    op.drop_table("person_filters")
    op.drop_table("org_credentials")
    op.drop_index(op.f("ix_merge_suggestions_status"), table_name="merge_suggestions")
    op.drop_index(
        op.f("ix_merge_suggestions_person_b_id"), table_name="merge_suggestions"
    )
    op.drop_index(
        op.f("ix_merge_suggestions_person_a_id"), table_name="merge_suggestions"
    )
    op.drop_table("merge_suggestions")
    op.drop_index(op.f("ix_identities_person_id"), table_name="identities")
    op.drop_index(
        "ix_identities_github_login_key",
        table_name="identities",
        postgresql_where="kind = 'github_login'",
        sqlite_where="kind = 'github_login'",
    )
    op.drop_index(
        "ix_identities_git_author_key",
        table_name="identities",
        postgresql_where="kind = 'git_author'",
        sqlite_where="kind = 'git_author'",
    )
    op.drop_table("identities")
    op.drop_table("settings")
    op.drop_table("reports")
    op.drop_table("report_schedules")
    op.drop_table("recipients")
    op.drop_table("persons")
    op.drop_index(op.f("ix_orgs_login"), table_name="orgs")
    op.drop_table("orgs")
    op.drop_table("job_ledger")
    op.drop_table("insights")
    # ### end Alembic commands ###
